# Generated by Django 5.0.6 on 2024-06-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Location'),
        ),
    ]
