# Generated by Django 5.0.6 on 2024-07-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='reciepient',
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
